server {
    server_name mauroacosta.com;

    location / {
        proxy_pass http://127.0.0.1:3005;
        include proxy_params;
    }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/mauroacosta.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mauroacosta.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    server_name www.mauroacosta.com;
    return 301 https://mauroacosta.com$request_uri;

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/mauroacosta.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mauroacosta.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    listen 80;
    server_name mauroacosta.com www.mauroacosta.com;
    return 301 https://mauroacosta.com$request_uri;
}
